services:
  jobert_db:
    container_name: postgres-jobert
    image: postgres:17
    environment:
      POSTGRES_USER: timmagee
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobert_db
    volumes:
      - jobert_data:/var/lib/postgresql/data
    ports:
      - "5333:5432"
    networks:
      - db
    restart: unless-stopped

  backend:
    container_name: jobert-backend
    build:
      context: ./backendSB
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - jobert_db
    restart: unless-stopped

  frontend:
    container_name: jobert-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  jobert_data:
