services:
  jobert_db:
    container_name: postgres-jobert
    image: postgres:17
    environment:
      POSTGRES_USER: timmagee
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobert_db
    volumes:
      - jobert_data:/var/lib/postgresql/data
    ports:
      - "5333:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  jobert_data:
