apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobert-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobert-backend
  template:
    metadata:
      labels:
        app: jobert-backend
    spec:
      containers:
        - name: backend
          image: jobert-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
