apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobert-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobert-db
  template:
    metadata:
      labels:
        app: jobert-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: jobert_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: jobert-db-pvc
