spring.application.name=backendSB
spring.datasource.url=jdbc:postgresql://localhost:5333/jobert_db
spring.datasource.username=timmagee
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
