# Generated by Django 4.2.23 on 2025-07-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('base_url', models.TextField(unique=True)),
                ('search_path', models.TextField()),
                ('search_query', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('job_desc', models.TextField()),
                ('min_experience', models.IntegerField(blank=True, null=True)),
                ('max_experience', models.IntegerField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Joblocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'JobLocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.TextField()),
                ('is_remote', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
    ]
